@echo off

set CONTAINER_FILE_PATH=%1
set MAYBE_AUDIO_OUT_FILE_PATH=%2

set AUDIO_OUT_FILE_OPTION=
if not _%MAYBE_AUDIO_OUT_FILE_PATH%==_ set AUDIO_OUT_FILE_OPTION=-out %MAYBE_AUDIO_OUT_FILE_PATH%
mp4box -raw 2 %CONTAINER_FILE_PATH% %AUDIO_OUT_FILE_OPTION%
